### ISSUE TITLE
Does MPU-9150/9250 need calibration regardless of calibration9250.h in lib?

### ISSUE THREAD

**Issue by west33** [mjs513/FreeIMU-Updates#16]
Does MPU-9150/9250 need calibration regardless of calibration9250.h in lib?

**Comment by mjs513** [comment]
You should always calibrate for your sensor. You can try the calibration
file that I came up with as a start but you may get more drifting.

Mike

**Comment by xsari3x** [comment]
Which calibration file you use for mpu 9150 ?

**Comment by mjs513** [comment]
You should always calibrate for your sensor there will be calibration differences from chip to chip. There is not one posted for the 9150 so you will have to create it.  The calibration file is always called calibration.h.  Follow the instructions on the wiki calibration page.
