### ISSUE TITLE
Changing target pins?

### ISSUE THREAD

**Issue by OffWhite-Russian** [mjs513/FreeIMU-Updates#22]
I am very new with Arduinos, but I am working on a project which requires me to stream data from the Sparkfun 6DOF IMU to my phone via the BLE function on my RedBear Blend Micro.  The Sparkfun works when connected to Arduino Uno just fine, but I cannot even get serial response when the IMU is connected to the Blend Micro.  Do I have to change the pin it writes to somewhere?

**Comment by mjs513** [comment]
Well, this really isn't a library issue but here is your answer.  I just looked at the pin layout for the board and it looks like sda is pin d2 and scl is pin d3.  You need to look at the pin function and just make sure you hook it up accordingly. on the uno its 4 and 5 respectively.

**Comment by OffWhite-Russian** [comment]
Thanks!!!!
