### ISSUE TITLE
Compilation error with Altimu10

### ISSUE THREAD

**Issue by grezco** [mjs513/FreeIMU-Updates#32]
Hello Mike,

I have a compilation error with the use of AltIMU10 in FreeIMU.h  (FreeIMU_raw sketch)

...\Arduino\libraries\FreeIMU\FreeIMU.cpp: In member function 'void FreeIMU::init0(bool)':
...\Arduino\libraries\FreeIMU\FreeIMU.cpp:733:2: error: expected ';' before 'compass' 
 compass.init();

Have you an idea of the problem ?

**Comment by mjs513** [comment]
Just  did a compile and found that there is a missing semi-colon at line 733 in the FreeIMU.cpp file.  Line should read:
```c++
	gyro_sensitivity = 70.0f;
```
Just pushed the correction to Github.

Mike
