### ISSUE TITLE
IMUDuino once again

### ISSUE THREAD

**Issue by avihaybar** [mjs513/FreeIMU-Updates#40]
Hi, 
First of all, I'd like to thank you for all the work you've done. Going through your wiki and code really helped me a lot with my project. But I'd like to ask a few questions - 

I'm using IMUDuino from femto.io as my board. I liked this board since it was small and had an onboard IMU & BT. However, I find my self having trouble running FreeIMU on it. 
My project consists of an IMUDuino embedded inside a spoon, with the goal of recording its orientation for analysis. I Can calibrate the board using the GUI from your repository, however I cannot fit the 'Serial' example and many other examples on the board itself. I've seen this thread (https://github.com/mjs513/FreeIMU-Updates/issues/30) but could not find the mentioned 'barebone' branch. 

One important note is that I do not require real time processing of the data. Is there a way to record everything and apply Calibration / AHRS processing as a post process ? 

Thanks in advance, 
Avihay.

**Comment by mjs513** [comment]
Hi Avihay

Sorry for the delay in getting back to you.  Even with the Barebones loading the bluetooth and pressure sensor code is pushing the limits.  Here is the link with the replacement files that was posted in the issue 30: 

https://drive.google.com/folderview?id=0BwzZjH9KYYMDfjJDc2Q3M29KYnlSdm4xeXhJTWZoVmxNLW00S04xUzdKQmhqTzN5azllWkE&usp=sharing

Yes you could just transmit the raw values and port the code over for the calibration into the processing sketch but that would be quite a job - not difficult but time consuming.

Mike
