### ISSUE TITLE
Altimu 10 (version  4) and Adafruit 10-DOF

### ISSUE THREAD

**Issue by grezco** [mjs513/FreeIMU-Updates#41]
Hello,
To use Altimu10 v4 breakout wth FreeIMU, I replaced LPS331 Library by LPS pololu Library that is compatible with v3 and v4 ( https://github.com/pololu/lps-arduino ) , and changed the name library in FreeIMU.h
I also modified FreeIMU.cpp and FreeIMU.h for support Adafruit 10-DOF.

All seem to be correct...

[FreeIMU.cpp.txt](https://github.com/mjs513/FreeIMU-Updates/files/46445/FreeIMU.cpp.txt)
[FreeIMU.h.txt](https://github.com/mjs513/FreeIMU-Updates/files/46446/FreeIMU.h.txt)

**Comment by mjs513** [comment]
Morning

I will take a look and will update the files if there are no other gotchas.

Thanks for the update- Mike

**Comment by mjs513** [comment]
Looked through the changes and they should work.  Have you tested the code changes on the v4 and the adafruit 10dof IMUs?  - mike

**Comment by grezco** [comment]
Hello,

 

Yes Mike, I have tested both.

 

De : Mike S [mailto:notifications@github.com] 
Envoyé : mardi 1 décembre 2015 17:22
À : mjs513/FreeIMU-Updates
Cc : grezco
Objet : Re: [FreeIMU-Updates] Altimu 10 (version 4) and Adafruit 10-DOF (#41)

 

Looked through the changes and they should work. Have you tested the code changes on the v4 and the adafruit 10dof IMUs? - mike

**Comment by mjs513** [comment]
Just made the push and updated the example files to support the new library.  Made a couple of other minor fixes to the examples as well.  

Thanks Again for making the updates.

Mike
