### ISSUE TITLE
compilation for Teensy 3.2

### ISSUE THREAD

**Issue by dethegeek** [mjs513/FreeIMU-Updates#42]
Hi

I'm investifgating about comilation issues for Teensy 3.2

I noticed several type mismatch, in FreeIMU.h and FreeIMU.cpp 

int is not the same as int16_t.

Compilation passed after changinf int to int16_t. I have to check this chang does not breaks compilation for regular Arduino boards.

**Comment by mjs513** [comment]
To keep it consistent with other sketches change the  int16 to int for raw_values in the calib sketch and it works fine.  Becareful with changing it in the library itself.  You will probably find that it breaks some of the sensor.

Mike

**Comment by dethegeek** [comment]
OK, I'l try this way. Thanks

**Comment by mjs513** [comment]
Fixed with latest updates.

Mike
