### ISSUE TITLE
multiple libraries

### ISSUE THREAD

**Issue by mjecj** [mjs513/FreeIMU-Updates#49]
hello..
 i've been uploading a code but i got this error
 Multiple libraries were found for "nRF24L01.h"
 Used: D:\My Documents\Arduino\libraries\RF24-master
 Not used: D:\My Documents\Arduino\libraries\RF24-master can anyone help me with this please.?

**Comment by mjs513** [comment]
mjecj
Usually you get that error as a result of two libraries having the same file, in this case nRF24L01.h.  This is described in the used and not used. Check the directories and see whats in them. I am taking it that this is not a FreeIMU library issue as the lib does not use the RF24L01.  If this is a compiler issue I would suggest that you head over to the Arduino forum as well.
