### ISSUE TITLE
Converting Accelerometer Data into Velocity

### ISSUE THREAD

**Issue by kswain1** [mjs513/FreeIMU-Updates#50]
Is there any part of this library where I can convert the fusion data into velocity readings? Maybe using raw, pitch, and yaw values to show the speed of the motion sensor.

**Comment by mjs513** [comment]
There is no place directly in the library.  You would have to take the accelerometer readings, massage them then do a integration between the new and old readings.  There is alot of info out there on how to do this.  As a hint take a look at the ODO tab in one of the processing tabs that has the beginnings of what you want to so.

Mike

**Comment by kswain1** [comment]
Thanks for the response I will check out the ODO tab for guidance.
