### ISSUE TITLE
FreeIMU GUI Slow Read 

### ISSUE THREAD

**Issue by martinferris** [mjs513/FreeIMU-Updates#54]
Hi Mike,

I've managed to fit the serial sketch onto my Nano, but when I run the calibration sampling it seems to be only sampling at a rate of once every 1.5 or so seconds. From watching people's calibration videos, it should be considerably faster. Any ideas as to why?

**EDIT**: I've realized that the Nano Atmega328 I have is only an 8 bit processor and not 16 or 32. Is it possible to use the calibration with an 8 bit and how? With the stock calibration.h file, it's movement is accurate but has drift making the absolute position change.

Alternatively: I have a working sketch with Madgwicks algorithm from @kriswiner where the absolute position IS correct, but there is weird drift between finding that position. How do I incorporate the stock accelerator calibration.h values into that sketch?  I assume they fit somewhere in here:
```
   mpu.getAcceleration  ( &a1, &a2, &a3  );
    ax = a1 * 2.0f / 32768.0f; // 2 g full range for accelerometer
    ay = a2 * 2.0f / 32768.0f;
    az = a3 * 2.0f / 32768.0f;
```

**Comment by mjs513** [comment]
Try changing the baud rate in the sketch and python to 115200

**Comment by martinferris** [comment]
Doubled checked, they are both set to 115200 already

**Comment by mjs513** [comment]
Believe there is some code in the file that skips some data.  Can't remember exactly the lines but look around where it does the serial reads

Mine

**Comment by 1oginov** [comment]
Got the same problem, check line 398 in cal_gui.py:

**Comment by mjs513** [comment]
@1oginov has got it right. Just one bit of warning.  There is no such thing as a stock calibration.h file.  You need to do your own calibration for your IMU. Temperature, soft/hard iron effects can affect the calibration.  Let me know if this works out or there is another issue.
