### ISSUE TITLE
unable to compile FreeIMU file

### ISSUE THREAD

**Issue by petitGeGe** [mjs513/FreeIMU-Updates#59]
Hello,
first congratulation for your work.
I'm trying to play with a genuino 101 board and I'm having a problem with the FreeIMU.cpp file wich does'nt compile with an error. I'm using ATOM for compilation.

> .pioenvs/genuino101/FreeImu/FreeIMU.cpp:1645:14: error: lvalue required as left operand of assignment_
> sampleFreq = 1.0f / ((now - lastUpdate) / 1000000.0f);
> 

To me, this value member sampleFreq is properly defined in the freeIMU header
I don't succeed in error correction.
So if you have time to provide any clue, I would really appreciate.
Thanks in advance

Eric

**Comment by mjs513** [comment]
Please make sure that you have uncommented the FreeIMU.h file and all other boards commented.  I am using the IDE 1.6.7 with the latest version of the Curie software - 1.0.6.    I am using a regular PC.  My tests are on a Arduino 101.  Suggest that you do a google search for c++ lvalue if the problem persists.  Also please make sure you are using the latest version of the library.  Really, just the latest versions of the FreeIMU.h and FreeIMU.cpp files.
