### ISSUE TITLE
Can't build my board with FreeIMU_serial.ino

### ISSUE THREAD

**Issue by Hyeonjinkim** [mjs513/FreeIMU-Updates#64]
Hello,

I'm using a GY-88 IMU sensor and an arduino Uno. Even though I uncommented GY-88 and commented out curieIMU setting, I can't build up. Instead, I've got error messages :

Arduino: 1.6.7 (Mac OS X), Board: "Arduino/Genuino Uno"

Board Intel:i586:izmir_fg doesn't define a 'build.board' preference. Auto-set to: I586_IZMIR_FG
Board Intel:i586:izmir_fd doesn't define a 'build.board' preference. Auto-set to: I586_IZMIR_FD
Board Intel:i686:izmir_ec doesn't define a 'build.board' preference. Auto-set to: I686_IZMIR_EC
WARNING: Spurious .github folder in 'Adafruit NeoMatrix' library
WARNING: Spurious .github folder in 'Adafruit NeoPixel' library
Warning: platform.txt from core 'Arduino AVR Boards' contains deprecated recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}", automatically converted to recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}" -o "{preprocessed_file_path}". Consider upgrading this core.
FreeIMU_serial:173: error: missing binary operator before token "my3IMU"
Multiple libraries were found for "I2Cdev.h"
 Used: /Users/Kim_for13/Documents/Arduino/libraries/I2Cdev
 Not used: /Users/Kim_for13/Documents/Arduino/libraries/MotionDriver
Multiple libraries were found for "DebugUtils.h"
 Used: /Users/Kim_for13/Documents/Arduino/libraries/FreeSixIMU
 Not used: /Users/Kim_for13/Documents/Arduino/libraries/FreeIMUUtils
         #if IS_9DOM() && (!HAS_MPU9150()  && !HAS_MPU9250() && !HAS_ALTIMU10() && !HAS_ADA_10_DOF() && !HAS_LSM9DS0() && !HAS_LSM9DS1())          my3IMU.magn.getValues(&raw_values[0], &raw_values[1], &raw_values[2]);
                                                                                                                                                   ^
exit status 1
missing binary operator before token "my3IMU"

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by mjs513** [comment]
Not sure if its freeIMU or the IDE.  Looks like the IDE.  The first line of the compiler messages reference the Board Intel:i586... did you select Arduino uno as the board to compile.  Some of the other error messages look like you need to update the ide.  Not sure the lib is going to fit on the uno.
