### ISSUE TITLE
Issue with library CurieIMU

### ISSUE THREAD

**Issue by lessmar** [mjs513/FreeIMU-Updates#68]
Hi,

I have an issue with the library CurieImu. This library say me (when I tray to compile the file FreeImu_serial.ino) that it's need more libraries. I install all the libraries required but at the end, this is not consistent. Finally I have troubles with the code and the libraries that I have included. I saw that this library has been included in the last version. is it possible don't use this library?
Where can I obtain the version without this library?

I thought that this library is incompabible, why? I'll try with other arduino version and I have the same.

![image](https://cloud.githubusercontent.com/assets/23102412/19773528/2941a588-9c6a-11e6-91fa-1bb7908a8bba.png)

I'll try to use your code with sensors: LSM303DLCH and HMC5883L.

Thank you in advance.

**Comment by mjs513** [comment]
First you need to run Curie_FreeIMU_serial.ino file.  Also because of changes to the main CurieIMU library I updated the library to make the appropriate adjustments.  I tested it with my Curie and HMC5883L and works fine.  Just remember to calibrate it first.
