### ISSUE TITLE
FreeIMU.cpp maghead undefined

### ISSUE THREAD

**Issue by DarinFlippo** [mjs513/FreeIMU-Updates#73]
Compiling for curie - line 1712 in FreeIMU.cpp throws an error saying that maghead is undefined.  It appears as if it may have been omitted from the comment block just to it's left and above it.  This seems likely because the 101 does not have a magnetometer to my knowledge.  I have commented it out in the image below.

![image](https://cloud.githubusercontent.com/assets/7749424/21377855/5be79638-c707-11e6-9996-94562c2da71f.png)

**Comment by mjs513** [comment]
Hi Darin

At line 58 and 59 in the FreeIMU.h file there are two configurations setup for the CurieIMU one without a magnetometer attached and the second with a magnetometer attached.  Here are the lines you need to look for:

> 
> //#define CurieIMU
> #define CurieIMU_Mag
> 

If you don't have a mag attached uncomment the first define and comment out the second:

> #define CurieIMU
> //#define CurieIMU_Mag

I think that may be your problem.

Mike
