### ISSUE TITLE
Using Freeimu with ESP32 Thing

### ISSUE THREAD

**Issue by dvonhausen** [mjs513/FreeIMU-Updates#74]
I'm using "ESP32 Thing" (https://www.sparkfun.com/products/13907) with the GY-521. It works with little change to the code (need "#define HAS_EEPPROM 0" as there seems to be no EEPPROM). However, I get drifting badly and then it tries to lock in place for a few seconds, then jumps to a new orientation and drifts again. It does this over and over again. As the ESP32 Thing is such a cheap board with wifi and ble built in, it provides a great development board. It also has eagle files so it easy to mod the board.
Can you integrate freeIMU with ESP32? Thanks, Dave.

**Comment by mjs513** [comment]
Hi Dave.  I do not have a ESP32 and like you just need the let the program know that it has no eeprom.  I have no plans right now to pick one up, maybe in the future.  However, to get you started you need to make sure you do your calibration with the ESP32 attached and you may have to adjust the algorithm parameters a bit.  It is explained in the wiki pages.  Hope this helps.
