### ISSUE TITLE
Angular speed

### ISSUE THREAD

**Issue by barbosafs** [mjs513/FreeIMU-Updates#75]
Hello there,
I've been using your library for my project and it's great!
I only have one doubt (sorry, new to github, I don't know if this should be asked here...):
 - I am using the freeIMU to get yaw, pitch and roll angles. However, I also need the angular speeds. Does any part of the code gives me that?
I know I could derive the angles output, even if noisy, but a filtered approximation would be better. I also know I could get the gyros readings and rotate them to match YPR representation, but I don't think this is the best idea.
How would you suggest me? Does any of the filters implemented generates a angular speed estimation?

Thanks,
Fernando.

**Comment by mjs513** [comment]
Fernado.  Presently there are no routines that can be called directly to get the angular velocities. However, with that said buried in the algorithms (madgwick.h, ahrs.h etc) there should be a place where they calculate the rate of change of the quaternions.  From that you might be able to get your angular velocities.  You could also just calculate it from the euler angles (rate of change).

Here are some references:
http://lost-found-wandering.blogspot.com/2011/09/revisiting-angular-velocity-from-two.html

https://www.google.com/url?sa=t&rct=j&q=Adgwick+angular+rates+from+quaternion&source=web&cd=&ved=0ahUKEwjfxdvJ6tnRAhVLMSYKHfS3BaEQFggpMAM&url=https%3A%2F%2Fwww.princeton.edu%2F~stengel%2FMAE331Lecture9.pdf&usg=AFQjCNE64aWMYkBXyUFwQEFVpCwXlUYaaw

http://www.euclideanspace.com/physics/kinematics/angularvelocity/](https://www.google.com/url?sa=t&rct=j&q=Adgwick+angular+rates+from+quaternion&source=web&cd=&ved=0ahUKEwjfxdvJ6tnRAhVLMSYKHfS3BaEQFggpMAM&url=https%3A%2F%2Fwww.princeton.edu%2F~stengel%2FMAE331Lecture9.pdf&usg=AFQjCNE64aWMYkBXyUFwQEFVpCwXlUYaaw

http://www.euclideanspace.com/physics/kinematics/angularvelocity/

https://www.google.com/url?sa=t&rct=j&q=Adgwick+angular+rates+from+quaternion&source=web&cd=&ved=0ahUKEwjfxdvJ6tnRAhVLMSYKHfS3BaEQFggfMAA&url=https%3A%2F%2Fwww.astro.rug.nl%2Fsoftware%2Fkapteyn%2F_downloads%2Fattitude.pdf&usg=AFQjCNF2E4o5zIqNJdJv1TTTOV8EedPl5w

[https://www.google.com/url?sa=t&rct=j&q=Adgwick+angular+rates+from+quaternion&source=web&cd=&ved=0ahUKEwjfxdvJ6tnRAhVLMSYKHfS3BaEQFggzMAc&url=http%3A%2F%2Fdownloads.hindawi.com%2Fjournals%2Fijno%2F2015%2F503814.pdf&usg=AFQjCNG7ZioX2chB8S6aDGjr-zXBjEKWqg](https://www.google.com/url?sa=t&rct=j&q=Adgwick+angular+rates+from+quaternion&source=web&cd=&ved=0ahUKEwjfxdvJ6tnRAhVLMSYKHfS3BaEQFggzMAc&url=http%3A%2F%2Fdownloads.hindawi.com%2Fjournals%2Fijno%2F2015%2F503814.pdf&usg=AFQjCNG7ZioX2chB8S6aDGjr-zXBjEKWqg)
