### ISSUE TITLE
Issues with FreeIMU_Serial_ARM_CPU with Teensy 3.1

### ISSUE THREAD

**Issue by vishwam93** [mjs513/FreeIMU-Updates#77]
Hello

I am trying to interface the GY-521 Breakout Board with the Teensy 3.1 using the Arduino IDE through the FreeIMU Libraries. When I try to upload the sketch onto the board, I get an error saying that a particular file (eiaextensions.h) cannot be found (Screenshot Attached).

![arduino ide error](https://cloud.githubusercontent.com/assets/25410599/22401359/0d76047c-e58d-11e6-8aa8-0e950418b496.JPG)

Thanks in advance

**Comment by mjs513** [comment]
Please check that you have trendy 3.1 selected in the boards menu.  It looks like you compiling for the curie.

**Comment by vishwam93** [comment]
Hello

Worked like a charm.

Thanks!
