### ISSUE TITLE
Unable to run FreeIMU GUI application ,Error in Python pyqtgraph.opengl.items.GLScatterPlotItem.GLScatterPlot Item object

### ISSUE THREAD

**Issue by xsari3x** [mjs513/FreeIMU-Updates#8]
Hello ,

I tried the freeIMU GUI calibration system on both linux 64 bit and windows 7 64 bit, 

I got the same error in both 

Kindly find my question on stackoverflow

http://stackoverflow.com/questions/26191513/opengl-error-in-python-pyqtgraph-opengl-items-glscatterplotitem-glscatterplot-it

**Comment by fereshtemohebbi** [comment]
Dear
I try to use the calibration application on windows and exactly I installed the mentioned URL in wiki page of calibration. and also change the word to 2(I use arduino mega) and change both IMU serial and python library to 57600. First i got below error
:Traceback (most recent call last):
| File "C:\Python27\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 180, in drawItemTree
| i.paint()
| File "C:\Python27\lib\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 149, in paint
| glDrawArrays(GL_POINTS, 0, int(pos.size / pos.shape[-1]))
| AttributeError: 'list' object has no attribute 'size'

Also H = numpy.array([x, y, z, -y2, -z2, numpy.ones([len(x)])])
I change the pos in GLscatteritem to self.pos = np.array([0,3]) and I dont have error right now but after that when I connect the serial port the application crashes I just receive the connection successful and waitint to rest arduino but gui crashes. What should I have to do ?
I installed every thing in 32 bit.Could you please guide me
can some one help me pleaseeee?

**Comment by reycreator17** [comment]
Hi @xsari3x 

can you please show me the links of dependencies you've used in linux. I'm having "segmetation fault" when running the cal_gui.py

Thanks 

Rey
